# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  build_pdf:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: registry.gitlab.com/mark.e.royer/texlive-full-with-emacs:20210611

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Build PDFs
        run: make

      - name: Upload PDFs
        uses: actions/upload-artifact@v2
        with:
          name: pdf-examples
          path: |
            beamer-example.pdf
            example.pdf
